### PR TITLE
Update to Elm 0.18

### PR DESCRIPTION
**Pull request by gaborv**
I mainly accepted the changes made by elm-format. 
The dependencies to elm-lang/core as well as to fredcy/elm-parseint were updated too.

I tested the outcome as part of a larger application and all looked fine.

### CODE REVIEW

**Comment by eskimoblood** [comment]
Could you please check why the tests are failing on travis, does they run on your local machine?

**Comment by gaborv** [comment]
I beieve they are failing because it tries to use Elm 0.17, and I did not allow that in elm-packages.json.

Get Outlook for iOS

On Mon, Nov 14, 2016 at 6:32 PM +0100, "Andreas Köberle" notifications@github.com wrote:

Could you please check why the tests are failing on travis, does they run on your local machine?

##

**Comment by eskimoblood** [comment]
Ah I think I remember it from the last time, I have to clear the cache in travis

**Comment by eskimoblood** [comment]
was a bit more work to get the test running, but now the updated version is published and ready to use

**Pull request merged**
