### PR TITLE
Add scaling functions

### PR DESCRIPTION
**Pull request by bgourlie**
Implement a couple of scaling methods in a fashion similar to how they're implemented in [Sass](http://sass-lang.com/documentation/Sass/Script/Functions.html#scale_color-instance_method).

I need these functions for use with [elm-css](https://github.com/rtfeldman/elm-css).  I figured I'd try and get them merged into an established library before creating a separate package!

### CODE REVIEW

**Comment by eskimoblood** [comment]
Hi Brian,

thanks for the pull request. Could you please improve the documentation for people that are not familiar with the SASS functionality. I had to switch to the SASS docs to understand why its implemented like this. Maybe you can summarise these section from the SASS docs in one or two sentences:

> That means that lightening an already-light color with scale-color won’t change the lightness much, but lightening a dark color by the same amount will change it more dramatically. This has the benefit of making scale-color($color, ...) have a similar effect regardless of what $color is.
> 
> For example, the lightness of a color can be anywhere between 0% and 100%. If scale-color($color, $lightness: 40%) is called, the resulting color’s lightness will be 40% of the way between its original lightness and 100. If scale-color($color, $lightness: -40%) is called instead, the lightness will be 40% of the way between the original and 0.

**Comment by bgourlie** [comment]
Done 👍

**Comment by eskimoblood** [comment]
Thanks again, its merged and the package is published. 

Btw you missed to add the 2 new function to the `@doc` at the top of the file. Next time run the `elm-package diff` to check if the package is ready to get published.

**Comment by bgourlie** [comment]
Ahh, thanks for the heads up!

**Comment by bgourlie** [comment]
I just noticed that the way I wrote the docs are causing them to render incorrectly [here](http://package.elm-lang.org/packages/eskimoblood/elm-color-extra/3.1.0/Color-Manipulate).  I will submit another PR tonight to fix.  Lesson learned: `elm-package diff` and verify the docs render correctly!

**Pull request merged**
