### PR TITLE
Fix CEILAB to RGB conversion

### PR DESCRIPTION
**Pull request by mattrrichard**
There were 2 issues that I fixed here:
1. There was a coefficient missing a negative sign that caused the blue channel to go wonky
2. It was sometimes possible to get rgb values outside 0-255 when converting from lab to rgb

### CODE REVIEW

**Comment by mattrrichard** [comment]
I don't have a clue what is up with that travis build failure.  It got a js error when trying to run the tests.  I'm going to try closing and reopening the PR to make it run again.

**Comment by mattrrichard** [comment]
I don't have any experience with Travis CI to know what is up, but I can't reproduce this issue locally.  It works from a fresh checkout with the same version of node being used there.  I'm baffled.

**Comment by eskimoblood** [comment]
Its not your fault, tested it again in the main branch and it happens there as well. I'll fix it then I merge your branch thanks for your fix.

**Comment by eskimoblood** [comment]
Mhmm also happen locally, but deleting the elm-stuff folder fixed it. Will merge it anyway.

**Pull request merged**
