### PR TITLE
Upgrade module for Elm 0.17

### PR DESCRIPTION
**Pull request by glenjamin**
Here's what I did:
- Bumped dependencies to their 0.17 equivalents
- Ran `elm-format` on every file (which automatically fixed 0.16->0.17 syntax)
- Fixed up the `test` folder based on https://github.com/elm-community/elm-test/pull/4

If you like, I can also send a PR with the required stuff to run this on Travis, you'd need to enable the project in their settings page for that to take effect.

Thanks!

### CODE REVIEW

**Comment by eskimoblood** [comment]
Thanks @glenjamin, but please consider to not add the formatting changes the next time cause its really hard to read the diff.

**Comment by eskimoblood** [comment]
And it would be really cool if you could add the changes to run the test on travis.

**Comment by glenjamin** [comment]
Yeah, sorry about the formatting stuff - I wouldn't normally have touched formatting, but having `elm-format` autofix the syntax was too tempting :)

**Comment by glenjamin** [comment]
eugh, I've just realised I've committed a generated file. I did add it to `.gitignore`, but only after staging it.

Not my finest PR! 😞

**Pull request merged**
